allowBuilds:
  esbuild: true
  unrs-resolver: true
  workerd: true
minimumReleaseAgeExclude:
  - '@cloudflare/workers-types@5.20260801.1'
  - jose@6.2.6
  - miniflare@5.20260730.0-alpha
  - wrangler@4.118.0
