export const contentReadinessItems = [
  'Official logo and brand guidance',
  'Official domain and final organisation-name styling approval',
  'Optional longer President message and named portrait credit',
  'Final About copy approval, leadership terms/profiles and Constitution',
  'Office address, public phone number and official social links',
  'Membership and donations information',
  'Nuclear Horizons author and submission route',
  'Verified launch news and events',
  'Future featured-research selections and canonical web references',
  'Student resources and opportunity owners',
  'Verified institution and map dataset',
  'Scientist profiles and member-highlight approvals',
  'Privacy policy and content-correction contact',
] as const
